name: logica_hs_collaudo
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_libserialport: ^0.6.0
  modbus_client_serial: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

